### ISSUE TITLE
Not getting the second email half the time

### ISSUE THREAD

**Issue by WEEZOOKARP** [Coffeelot/cw-boostjob#1]
![image](https://user-images.githubusercontent.com/76672483/183269962-a2fbf8af-571d-4c0f-afa2-a2a69910ca40.png)

**Comment by Coffeelot** [comment]
Hmm, looking into this. 

Were your characters job set to police mayhap?

**Comment by WEEZOOKARP** [comment]
yes

**Comment by Coffeelot** [comment]
Fixed some stuff regarding that yesterday. Not sure if it's related. Try the latest patch.
